### ISSUE TITLE
HTTP Timeout does not work

### ISSUE THREAD

**Issue by szerwi** [tobiasschuerg/InfluxDB-Client-for-Arduino#149]
Here are my client's settings:

```
influxdb.setWriteOptions(WriteOptions().writePrecision(precision).batchSize(1).bufferSize(360).flushInterval(3600).retryInterval(5).maxRetryInterval(300).maxRetryAttempts(0));
influxdb.setHTTPOptions(HTTPOptions().httpReadTimeout(4000));
```

In connection params I set the address that does not exist.

__Expected behavior:__
```influxdb.writePoint()``` should fail after 4 seconds.

__Actual behavior:__
It fails after about 15 seconds.

__Specifications:__
 - Library Version: 3.8.0
 - InfluxDB Version: 2.0.7
 - Board/ESP chip: ESP32
 - Device Arduino SDK version: ESP32 2.0.0-alpha1

**Comment by vlastahajek** [comment]
@szerwi, thanks for raising this issue.  You are most probably using HTTPS for connecting to the server.
[There is a problem](https://github.com/esp8266/Arduino/issues/8203) that underlying `WifiClientSecure` has hardcoded timeout for establishing a secured connection 15s.
The overall initial client timeout is about 20s, because there is the MFLN negotiation before the first server request is sent, which has a hardcoded timeout 5s. And then comes the server request that timeouts in 15s.

**Comment by szerwi** [comment]
Hi. Unfortunately, I'm using HTTP on ESP32, not ESP8266.

**Comment by vlastahajek** [comment]
Aha, my bad, sorry, I've overlooked your info, let me check again..

**Comment by vlastahajek** [comment]
@szerwi, it is possible set connection timeout for ESP32 for HTTP connection. But it will not work for HTTPS, because timeout connection is not implemented there yet.

**Comment by szerwi** [comment]
@vlastahajek For the HTTP connection, do I need to set it using ESP32 libraries or using Influxdb library and functions that I've posted above?

**Comment by vlastahajek** [comment]
@szerwi, I've pushed the fix for this library. Just update the library from the master. No need to do any changes in your sources.

**Comment by szerwi** [comment]
Why setting the timeout still won't work over HTTPS? Is it dependet from you or is it a bug in ESP32 libraries?

**Comment by vlastahajek** [comment]
It is problem in the WifiClientSecure in the ESP32 SDK (tested in 1.0.6). I will post new issue there  later.

**Comment by vlastahajek** [comment]
FYI, [my fix for ESP32](https://github.com/espressif/arduino-esp32/pull/5418) is merged. It should be part of the next release.
